### PR TITLE
[#42] Add base URL to AJAX URL call

### PR DESCRIPTION
**Pull request by skillmatic-co**
Adding in a base_url setting would be a solution to #42

### CODE REVIEW

**Review by itmammoth — CHANGES_REQUESTED** [review]
Thx!
Can you change `base_url` to camel case?

**Comment by skillmatic-co** [comment]
Done. Sorry, I've been in Ruby mode.

**Review by itmammoth — APPROVED** [review]
LGTM

**Comment by skillmatic-co** [comment]
Thanks! This solved my issue.

**Pull request merged**
